defaults: &defaults
  admin_username: admin
  admin_password: aaf4c61ddcc5e8a2dabede0f3b482cd9aea9434d # = 'hello'

development:
  <<: *defaults

test:
  admin_username: admin
  admin_password: aaf4c61ddcc5e8a2dabede0f3b482cd9aea9434d # = 'hello'

production:
  <<: *defaults